name: SynKno
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - ipykernel
  - pytorch
  - transformers
  - chromadb
  - requests
  - pip:
      - openai
      - python-dotenv
      - pydantic